# Generated by Django 5.0.8 on 2024-08-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_todoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="is_complete",
            new_name="is_completed",
        ),
        migrations.RenameField(
            model_name="todoitem",
            old_name="list",
            new_name="items",
        ),
    ]
