# Generated by Django 5.0.8 on 2024-08-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_rename_is_complete_todoitem_is_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="items",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="todos.todolist",
            ),
        ),
    ]
